# Generated by Django 4.2.2 on 2023-09-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comments_remove_post_updated_date_replay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sells',
            field=models.IntegerField(default=0),
        ),
    ]
